# Generated by Django 5.1.4 on 2025-01-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AviaSales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='co_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pilot_of', to='AviaSales.crewmember'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='navigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigator_of', to='AviaSales.crewmember'),
        ),
    ]
